name: "Nostradamus"
description: "ML-powered sensor forecasting for Home Assistant. Predict any numeric sensor using historical data and user-selected supporting sensors."
version: "0.1.1"
slug: "nostradamus"
image: "ghcr.io/schieska/nostradamus-{arch}"
init: false
arch:
  - aarch64
  - amd64
homeassistant_api: true
hassio_api: true
hassio_role: default
map:
  - type: data
    read_only: false
ports:
  5000/tcp: null
options: {}
schema: {}
